7.20f MAR 29  2026

diff --git a/looma shell scripts/loomaAWStoMAC b/looma shell scripts/loomaAWStoMAC
--- a/looma shell scripts/loomaAWStoMAC
+++ b/looma shell scripts/loomaAWStoMAC
@@ -1,19 +1,14 @@
 #!/bin/bash
 #
 #  filename: loomaAWStoMAC
-#       VERSION 1.3
+#       VERSION 1.2
 #       author: skip
-#       date:   JUL 2021 / MAY 2026
+#       date:   JUL 2021
 #
-#  used to backup looma code, database and content from
-#    Looma Online on AWS (looma.website) to Skip's iMac
+#  used to backup looma code, database and content from Looma Online on AWS to Skip's iMac
 #
-#  the target iMac folders are then automatically sync'd with
-#    Dropbox > 09 Looma Backup AWS in folders "Looma" and "content"
-#
-#  log of the operation is stored in "/Users/skip/Desktop/Looma Backup Logs (AWStoMAC)/loomabackuplogfile_$(date +%F-%T)"
-#
-#  run with "crontab" at 12:30am (after the daily mongodump on AWS saves the latest DB contents into "  ")
+#  the target iMac folders are also automatically sync'd with
+#    Dropbox > 03 Content Reference > 01 Content > D Finished Content > Content on Looma
 #
 #  can be called with a parameter "dryrun" in which case the transfers are not performed,
 #    configured to be run on a MAC
@@ -41,22 +36,25 @@
 #--progress show transfer progress
 #--stats    print stats at the end
 #
+
 log() {
 	echo "--------$1" >> $logfile
 }
 
 result () {
-    if [[ $1 -ne 0 ]]
-    then
-        log ""
-        log "ERROR: previous operation returned $1"
-    else
-        log ""
-        log "operation successful"
-    fi
+   if [[ $1 -ne 0 ]]
+	then
+       log ""
+       log "ERROR: previous operation returned $1"
+   else
+       log ""
+       log "operation successful"
+   fi
 }
 
-logfile="/Users/skip/Desktop/Looma Backup Logs (AWStoMAC)/loomabackuplogfile_$(date +%F-%T)"
+TARGET="/Users/skip/Dropbox/09-Looma-AWS-Backup"
+
+logfile="/$TARGET/Looma-AWS-Backup-Logs/loomabackuplogfile_$(date +%F-%T).txt"
 touch $logfile              #create log file if not there
 cp  /dev/null   $logfile    #empty log file
 
@@ -64,63 +62,70 @@ cp  /dev/null   $logfile    #empty log file
 log "   "
 log "  - - - - - - running loomaAWStoMAC script - - - - - -"
 log "  - - - - - - this log file is $logfile - - - - - -"
-log "script loomaAWStoMAC: Looma backup from AWS to Mac, last run date: `date`"
+log "script loomaAWStoMAC: Looma backup from AWS to Mac on: `date`"
 
 HOSTNAME=`hostname`
 log "host is $HOSTNAME"
 
-TARGET="/Users/skip/Dropbox/09 Looma Backup AWS"
 
 cd  "$TARGET"
 
 if [[ `pwd` !=  $TARGET ]]
-   then
-       log
-       log " - - - ERROR - - -"
-       log "  Didnt find target folder on the MAC"
-       log "  Be sure this folder exists: $TARGET"
-       exit 1
-    fi
+  then
+      log
+      log " - - - ERROR - - -"
+      log "  Didnt find target folder on the MAC"
+      log "  Be sure this folder exists: $TARGET"
+      exit 1
+   fi
 
 
 mkdir -p Looma     #in case its not already there
 mkdir -p content   #in case its not already there
 
-AWS="ubuntu@ec2-34-210-116-58.us-west-2.compute.amazonaws.com"
+AWS="bitnami@ec2-54-212-244-82.us-west-2.compute.amazonaws.com"
 
 log
-log "- backing up Looma code"
+log "- sync'ing Looma code from AWS to $HOSTNAME"
 
 SECONDS=0
-    if [[ $1 = "dryrun" ]]
-    then
-        rsync -az --dry-run --delete --perms --stats --update --progress  --exclude '.[!.]*' -e "ssh -i /Users/skip/Desktop/looma.pem"  $AWS:htdocs/Looma/  ./Looma
+   if [[ $1 = "dryrun" ]]
+   then
+       rsync -az --dry-run --delete --perms --stats --update --progress  --exclude '.[!.]*' -e "ssh -i /Users/skip/Desktop/keys/looma3.pem"  $AWS:/opt/bitnami/apache/htdocs/Looma $TARGET/Looma
+       result $?
+   else
+        rsync -e "ssh -i /Users/skip/Desktop/keys/looma3.pem" \
+        -az --delete --perms --stats \
+        --update --progress  --exclude '.[!.]*' \
+        $AWS:/opt/bitnami/apache/htdocs/Looma $TARGET/Looma
+
         result $?
-    else
-        rsync -aqz           --delete --perms --stats --update --progress  --exclude '.[!.]*' -e "ssh -i /Users/skip/Desktop/looma.pem"   $AWS:htdocs/Looma/  ./Looma >> $logfile
-        result $?
-    fi
+   fi
 log "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds elapsed."
 
 log
 log "- backing up Looma content"
 
-    SECONDS=0
-    if [[ $1 = "dryrun" ]]
-    then
-        rsync -az --dry-run --size-only --delete --perms --stats --update --progress  --exclude '.[!.]*' -e "ssh -i /Users/skip/Desktop/looma.pem"   $AWS:htdocs/content/  ./content
+   SECONDS=0
+   if [[ $1 = "dryrun" ]]
+   then
+       rsync -az --dry-run --size-only --delete --perms --stats --update --progress  --exclude '.[!.]*' -e "ssh -i /Users/skip/Desktop/keys/looma3.pem"   $AWS:/opt/bitnami/apache/htdocs/content $TARGET/conten
+       result $?
+   else
+      rsync -e "ssh -i /Users/skip/Desktop/keys/looma3.pem" \
+	    -az --size-only --delete --perms --stats \
+	    --update --progress  --exclude '.[!.]*' \
+	    $AWS:/opt/bitnami/apache/htdocs/content $TARGET/content
+
         result $?
-    else
-        rsync -aqz    --size-only --delete --perms --stats --update --progress  --exclude '.[!.]*' -e "ssh -i /Users/skip/Desktop/looma.pem"   $AWS:htdocs/content/  ./content >> $logfile
-        result $?
-		fi
+    fi
 log "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds elapsed."
 
 log
-    if [[ $1 = "dryrun" ]]
-    then
-      log "DRYRUN LOOMA BACKUP: no files moved"
-    else
-      log "DONE LOOMA BACKUP: sync'ed Looma code, database and content on AWS to this MAC"
-   fi
+   if [[ $1 = "dryrun" ]]
+   then
+     log "DRYRUN LOOMA BACKUP: no files moved"
+   else
+     log "DONE LOOMA BACKUP: sync'ed Looma code, database and content on AWS to this MAC"
+  fi
 log
