2024 MAY version 7.9.15 improved 'loomaupdate' new 2024 textbooks

diff --git a/looma shell scripts/loomaupdater b/looma shell scripts/loomaupdater
--- a/looma shell scripts/loomaupdater
+++ b/looma shell scripts/loomaupdater
@@ -1,9 +1,9 @@
 #!/bin/bash
 #
 #  filename: loomaupdater
-#       VERSION 6.0 for rysnc.net
+#       VERSION 7.0
 #       author: skip
-#       date:   SEP 2021, FEB 2024
+#       date:   SEP 2021, FEB 2024, MAY 2024
 #
 #     revised OCT 2023 to check 'archivetimestamp.txt' to see if an update is needed
 #       on both /Looma and /content
@@ -43,6 +43,7 @@
 #   -g  preserve group
 #   -o  preserve owner
 #   -D  transfer devices and specials (NA for Looma)
+#   -O  omit-dir-times
 #   -z  	use compression
 #--dry-run
 #--progress
@@ -71,7 +72,8 @@ result () {
 }  #  end result()
 
 pause () {
-   read -p "Paused, press [Enter] to continue"
+   echo " Paused $1"
+   read -p "     press [Enter] to continue"
 }  #  end pause()
 
 backup () {
@@ -82,13 +84,13 @@ backup () {
     echo -n  "- - continue ('n' recommended) [y/n]?"; read input;
     if [[ $input = "y" ]]
     then
-        if [ -d "$TODIR/LoomaBAK" ]
+        if [ -d "$TO/LoomaBAK" ]
         then
           echo "- deleting old LoomaBAK directory"
-          sudo rm -r "$TODIR/LoomaBAK"
+          sudo rm -r "$TO/LoomaBAK"
           result $?
         fi
-        mv    "$TODIR/Looma"   "$TODIR/LoomaBAk"
+        mv    "$TO/Looma"   "$TO/LoomaBAk"
         result $?
     else
         echo " - - - SKIPPED: backing up Looma code "
@@ -120,66 +122,50 @@ checknetworkspeed () {
     fi
 }  #  end checknetworkspeed()
 
-
-# check if the timestamp of current files is same as timestamp of the archive
 # return 1 if timestamps are equal [so no update is needed]
-checktimestamp () {
-  #echo "  *** *** if prompted for \"password:\" enter \"looma\"  *** ***"
+checktimestamp () {         # uses $FROM, $TO, and $DIR ['Looma' | 'content']
+
+# get timestamp of files currently on this Looma
+  if [[ -f $TO/$DIR/archivetimestamp.txt ]]
+   then
+     current=`cat $TO/$DIR/archivetimestamp.txt`
+   else
+     current="none"
+   fi
+
+# get timestamp of files on Looma Archive Server
   if [[ $source = "I" ]]
   then
-    if [[ -f $TO/$DIR/archivetimestamp.txt ]]
-    then
-      current=`cat $TO/$DIR/archivetimestamp.txt`
-    else
-      current=""
-    fi
-
-  # latest=                 `ssh $FROM cat ../$DIR/archivetimestamp.txt`
-    latest=`sshpass -p looma ssh $FROM cat ../$DIR/archivetimestamp.txt`
-
-    if [[ $current = $latest ]] 
-    then
-      echo "current timestamp for $DIR is $current"
-      echo "latest timestamp for archive is $latest"
-      return 1
-    fi
+      if [[ `which sshpass` != "" ]]
+      then
+        latest=`sshpass -p looma ssh $FROM "cat $DIR/archivetimestamp.txt"`
+      else
+        echo "enter password 'looma' if requested"
+        latest=`ssh $FROM "cat $DIR/archivetimestamp.txt"`
+      fi
   else
-    if [[ -f $TO/$DIR/archivetimestamp.txt ]]
-    then
-      current=`cat $TO/$DIR/archivetimestamp.txt`
-    else
-      current=""
-    fi
-
-    latest=`cat $FROM/$DIR/archivetimestamp.txt`
-    if [[ $current = $latest ]] 
-    then
-      echo "current timestamp for $DIR is $current"
-      echo "latest timestamp for archive is $latest"
-      return 1
-    fi
+     latest=`cat $FROM/$DIR/archivetimestamp.txt`
   fi
-  return 0
+
+#pause "in checktimesamp, current = $current, latest = $latest"
+
+# check if timestamps are equal
+  if [[ $current = $latest ]]
+  then
+    echo " - - Current timestamp for $DIR is   $current"
+    echo " - - Latest timestamp for archive is $latest"
+    return 1
+  else
+    return 0
+  fi
 }  #  end checktimestamp()
 
 #function DOSYNC() to exec the rsync. global var $DRYRUNMODE is either "--dry-run" or ""
-# call dosync() with $1 = the source , $2 = the target $3 = the directory, $4 = "--sizeonly" or null
+# call dosync() with $FROM = the source , $TO = the target $2 = the directory "Looma" or "content", $2 = "--sizeonly" or null
 dosync () {
-    FROM=$1
-    TO=$2
-    DIR=$3
-    SIZEONLY=$4
 
-    echo;
-
-    checktimestamp
-    if [[ $? = 1 ]]
-      then
-        echo "++++++++++++++++++++++++"
-        echo "$TO/$DIR is UP TO DATE [No files are being transferred]"
-        echo "++++++++++++++++++++++++"
-        return 0
-      fi
+    DIR=$1
+    SIZEONLY=$2
 
     if [[ $source = "I" ]]
     then
@@ -188,8 +174,9 @@ dosync () {
       remote=$FROM
     fi
 
-    # avoids manual entry of password for rsync (doesnt work?0
+    # RSYNC_PASSWORD avoids manual entry of password for rsync (but, doesnt work?)
     # RSYNC_PASSWORD="looma"
+    echo "**********************************";
 
  if [[ $DRYRUNMODE = "--dry-run" ]]
     then
@@ -200,7 +187,11 @@ dosync () {
     echo
     #echo "  *** *** if prompted for \"password:\" enter \"looma\"  *** ***"
 
-      # NOTE, adding "O" option to avoid errors wioth modified date updates
+#pause "in dosync, which sshpass = `which sshpass`"
+
+    if [[ `which sshpass` != "" ]]
+      # NOTE, adding "O" option to avoid errors with modified date updates
+    then
     sshpass -p 'looma' rsync -azO  $DRYRUNMODE $SIZEONLY  \
         --stats  \
         --perms  --chmod=D777,F777 --chown=looma:looma \
@@ -208,6 +199,18 @@ dosync () {
         -e "ssh"   \
        "$remote/$DIR/"  "$TO/$DIR"
       # NOTE: RSYNC needs a slash after FROM dir and no slash after TO dir
+
+     # NOTE, adding "O" option to avoid errors with modified date updates
+    else
+      echo "enter password 'looma' if requested"
+      rsync -azO  $DRYRUNMODE $SIZEONLY  \
+        --stats  \
+        --perms  --chmod=D777,F777 --chown=looma:looma \
+        --exclude '.[!.]*' --delete --delete-excluded   \
+        -e "ssh"   \
+       "$remote/$DIR/"  "$TO/$DIR"
+      # NOTE: RSYNC needs a slash after FROM dir and no slash after TO dir
+    fi
 
   if [[ $DRYRUNMODE != "--dry-run" ]]
      then    echo
@@ -230,14 +233,16 @@ echo "Be sure you have read the instructions"
 echo "****************************************************************"
 
 
-if [[ $2 = "dryrun" ]]
+if [[ $1 = "dryrun" ]]
   then
     DRYRUNMODE="--dry-run"
   else
     DRYRUNMODE=""
 fi
 
-CUMULATIVE=0
+#pause "dryrunmode is $DRYRUNMODE, first param is $1"
+
+codetime=0
 
 #####################
 ##################### user input - choose update from USB stick or from Internet
@@ -251,7 +256,7 @@ then
 
 ###########################  sourcing from USB - settings  #############
 
-  FROMDIR="/media/odroid/LOOMA/loomaupdate"
+  FROM="/media/odroid/LOOMA/loomaupdate"   # for Linux (different for MAC)
 
       echo; echo "****************************************************************"
       echo "    you must insert a USB memory stick which is named LOOMA"
@@ -259,7 +264,7 @@ then
       echo "    the USB stick must have the files to be uploaded stored in a top-level folder named 'loomaupdate' "
       echo "****************************************************************"
 
-      cd "$FROMDIR" # for Linux (different for MAC)
+      cd "$FROM"
 
       if [ "$?" -ne 0 ]
       then
@@ -275,7 +280,8 @@ then
 
   elif [[ $source = "I" ]]
   then
-      FROMDIR="58191@usw-s008.rsync.net"
+      # URL for rsync.net Looma Archive Server
+      FROM="58191@usw-s008.rsync.net"
 
     echo; echo "****************************************************************"
     echo "-   *** you can check network speed before proceeding"
@@ -295,107 +301,87 @@ then
 
 echo "********************"
 
-  if [ $# -eq 0 ]
-    then
-     TODIR="/var/www/html"
-    else
-     TODIR=$1
-  fi
+ TO="/var/www/html"
 
-   if [ ! -d $TODIR/Looma ];
+   if [ ! -d $TO/Looma ];
      then
        echo "Target directory does not contain a /Looma folder"
        exit
     fi
 
-###########################  do the transfers ###############
-
-#       copy current Looma code to LoomaBAK
-#       NOTE: call to function DACKUP() commented out for now
+###############  do the transfers ###############
+#################################################
+    #       copy current Looma code to LoomaBAK
+    #       NOTE: call to function DACKUP() commented out for now to save time
     # backup
 
-    # echo; echo "if prompted for \"password for odroid\" enter \"odroid\"  "
+    DIR="Looma"
+    checktimestamp
+    
+   #pause "after code timestamp latest is $latest, current is $current"
+    
+    if [[ $? = 1 ]]
+      then
+        echo "++++++++++++++++++++++++"
+        echo "$TO/$DIR is UP TO DATE [No files are will be transferred]"
+        echo "++++++++++++++++++++++++"
+      else
 
-    #       install new Looma code
-    echo
-    echo "****************************************************************"
-    echo "- preparing to update LOOMA CODE"
-    echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
-    if [[ $input = "y" ]]
-    then
+       #       install new Looma code
+        echo
+        echo "****************************************************************"
+        echo "- preparing to update LOOMA CODE"
+        echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
+        if [[ $input = "y" ]]
+        then
 
         #*************RSYNC*********************
         SECONDS=0
-
         #  for CODE we call dosync() with $4 (size-only) = null
-         echo
-         echo "starting to update code files. please wait ..."
-         echo
+        echo
+        echo "starting to update code files. please wait ..."
+        echo
 
-        dosync    "$FROMDIR"  "$TODIR" "Looma"
+        dosync "Looma"
 
         echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds elapsed."
-        CUMULATIVE=$SECONDS
+        codetime=$SECONDS
 
-        #clear browser cache so the new code files will be used
-       # if [[  -f "$TODIR/Looma/looma shell scripts/loomaClearChromiumCache" ]]
-        #then
-         # source "$TODIR/Looma/looma shell scripts/loomaClearChromiumCache"
-        #fi
-    else
-        echo " - - - SKIPPED: installing new Looma code"
-    fi
+        else
+          echo " - - - SKIPPED: installing new Looma code"
+        fi
 
-    #       install new Looma database
-#    echo
-#    echo "****************************************************************"
- #   echo "- preparing to update LOOMA DATABASE"
- #   echo "-   ***note: this will NOT erase any lesson plans or text files already in the database"
- #   echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
-
-#    if [[ $input = "y" ]]
-#    then
-
-    if [[ -d "$TODIR/Looma/mongo-dump/dump/looma" ]]
+        if [[ -d "$TO/Looma/mongo-dump/dump/looma" ]]
         then
-
-            # [mongorestore doesnt update existing mongoDB documents that have changes]
-            # to fix this, we use the following procedure:
-            #     temp save locally created documents (lessons and texts)
-            #     update all documents to latest version from the looma archive
-            #     then re-load the locally created documents
-            # mongoexport collections 'lessons' and 'text_files' to temp files
-            # drop db 'looma' so mongorestore from archives will update all documents in the db
-            # mongorestore db looma dump from looma archive on USB
-            # finally, mongoimport the temp files to collectons 'lessons' and 'text_files'
-            #      to re-instate locally created lessons and texts
-
-            #mongoexport --quiet --db looma --collection lessons --out /tmp/lessonsFromMongo.tmp
-            #mongoexport --quiet --db looma --collection text_files --out /tmp/textsFromMongo.tmp
 
             echo
             echo "starting to update Looma's database. please wait ..."
             echo
-            mongo --eval "db.dropDatabase();" looma
-            mongorestore --quiet --db looma "$TODIR/Looma/mongo-dump/dump/looma/"
+            mongo --quiet --eval "db.dropDatabase();" looma
+            mongorestore --quiet --db looma "$TO/Looma/mongo-dump/dump/looma/"
 
-            #mongoimport --quiet --db looma --collection lessons --file /tmp/lessonsFromMongo.tmp
-            #mongoimport --quiet --db looma --collection text_files --file /tmp/textsFromMongo.tmp
-
-            #rm /tmp/lessonsFromMongo.tmp
-            #rm /tmp/textsFromMongo.tmp
-
-            mongoimport --db loomausers --collection logins  --mode upsert --file "$TODIR/Looma/mongo-dump/logins/defaultlogins.json"
-            rm "$TODIR/Looma/mongo-dump/logins/defaultlogins.json"
-
-            result $?
-        else echo "ERROR: no source dir ($TODIR/Looma/mongo-dump/dump/looma) for mongo restore"
+            if [[ -f $TO/Looma/mongo-dump/logins/defaultlogins.json ]]
+            then
+               mongoimport --quiet --db loomausers --collection logins  --mode upsert --file "$TO/Looma/mongo-dump/logins/defaultlogins.json"
+               rm "$TO/Looma/mongo-dump/logins/defaultlogins.json"
+            fi
+        else echo "ERROR: no source dir ($TO/Looma/mongo-dump/dump/looma) found for mongo restore"
         fi
- #   else
- #       echo " - - - SKIPPED: installing new Looma database"
- #  fi
+    fi
 
+#################################################
     #       copy new files into "content" directory
+#################################################
+
+     DIR="content"
+     checktimestamp
+    if [[ $? = 1 ]]
+      then
+        echo "++++++++++++++++++++++++"
+        echo "$TO/$DIR is UP TO DATE [No files are will be transferred]"
+        echo "++++++++++++++++++++++++"
+      else
+
     echo
     echo "****************************************************************"
     echo "- preparing to update files in CONTENT directory"
@@ -408,21 +394,23 @@ echo "********************"
         echo
         echo "starting to update content files. this takes a long time. please wait ..."
         echo
-        dosync "$FROMDIR"  "$TODIR"  "content" "--size-only"
+        dosync "content" "--size-only"
 
         # uncomment to sync the maps [usually they dont change]
-        # dosync "$FROMDIR"  "$TODIR" "maps2018" "--size-only"
+        # dosync "$FROM"  "$TO" "maps2018" "--size-only"
 
         # uncomment to sync ePaath [usually doesnt change]
-        # dosync "$FROMDIR"    "$TODIR" "ePaath" "--size-only"
+        # dosync "$FROM"    "$TO" "ePaath" "--size-only"
 
         echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds elapsed."
-
+        contenttime=$SECONDS
     else
         echo " - - - SKIPPED: installing new Looma content"
     fi
+  fi
 
-  echo "Total $(( ($SECONDS + $CUMULATIVE) / 60)) minutes and $(( ($SECONDS + $CUMULATIVE)  % 60)) seconds elapsed."
+  echo "*****************************************"
+  echo "Total $(( ($contenttime + $codetime) / 60)) minutes and $(( ($contenttime + $codetime)  % 60)) seconds elapsed."
 
 echo
 echo "****************************************************************"
@@ -435,4 +423,5 @@ echo "****************************************************************"
  fi
 echo "****************************************************************"
 echo "****************************************************************"
+echo
 
